- postgresql_query:
    query: "update pg_database set datallowconn = TRUE where datname = 'template0';"

- postgresql_query:
    db: template0
    query: "update pg_database set datistemplate = FALSE where datname = 'template1';"

- postgresql_db:
    name: template1
    state: absent

- postgresql_db:
    name: template1
    template: template0
    encoding: UTF8

- postgresql_query:
    db: template0
    query: "update pg_database set datistemplate = TRUE where datname = 'template1';"

- postgresql_query:
    db: template1
    query: "update pg_database set datallowconn = FALSE where datname = 'template0';"
